# Site settings
title: Willyworks
email:
description: "北海道札幌市のクラウド・サーバサイドにおける設計・構築・開発・自動化（DevOps）・コンサルティングの副業スペシャリストがインフラからアプリケーションまでトータルで最適なシステムを作るお手伝いを致します。"
sub_title: Cloud/Server-side specialist will help you at part-time from Sapporo-shi, Hokkaido.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Masashi Terui
email: contact@willy.works
facebook_username: marcy.terui
twitter_username: marcy_terui
github_username: marcy-terui
address:
  - line: Hokkaido
  - line: Sapporo-shi
  # Feel free to add more lines here
telephone:
copyright: Willyworks

# API settings
google_api_key: UA-37193543-6

# Build settings
markdown: kramdown
