# Site settings
title: Willyworks
description: "北海道からクラウド・自動化（Infrastructure as Code, DevOps）を中心とした先進的なインフラの設計・構築や、その上でのアプリケーション開発までをトータルでサポート致します。"
sub_title: "A part-time cloud/server-side expert in Sapporo-shi, Hokkaido."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Masashi Terui
email: contact@willy.works
facebook_username: marcy.terui
twitter_username: marcy_terui
github_username: marcy-terui
address:
  - line: Hokkaido
  - line: Sapporo-shi
  # Feel free to add more lines here
telephone:
copyright: Willyworks

# API settings
google_api_key: UA-37193543-6

# Build settings
markdown: kramdown
